fix: Define naming convention for Events
eclipse-esmf/esmf-semantic-aspect-meta-model pull request #237
Opened 2023-07-03 11:44 UTC by Yauhenikapl

Changes:
- update docs for naming convention of Events.

2023-07-03 13:29 UTC, michelu89 approved these changes

2023-07-03 13:51 UTC, chris-volk requested changes
Hi all, 

the content is good and approved. But please make sure that you don't publish the change with the current version of SAMM. This should only go live with a new version.
Reason: The Aspect Model Editor currently does not allow UpperCamelCase, and I do not want the specification and the editor contradict each other.

2023-07-04 06:30 UTC, Yauhenikapl commented
@chris-volk 
Yes, thank you for clarification! Yes, you are right. This is ticket inform Model Editor team to do some changes in MetaModel Editor.

Thanks!

2023-07-04 13:17 UTC, chris-volk commented
Sorry, this can be merged immediately from content perspective. The editor enforces UpperCamelCase already which is what we want. Sorry for the confusion.

2023-07-05 13:46 UTC, chris-volk approved these changes

2023-07-10 06:37 UTC, atextor approved these changes

2023-07-10 06:39 UTC, merged