Add an example to payload documentation
eclipse-esmf/esmf-semantic-aspect-meta-model pull request #257
Opened 2023-10-13 15:55 UTC by KobOp

Fixes [#121](https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model/issues/121)

2023-10-16 11:43 UTC, Yauhenikapl approved these changes
Looks good!

2023-10-16 12:28 UTC, ysrbo approved these changes

2023-10-17 06:23 UTC, atextor requested changes

2023-10-17 06:23 UTC, atextor commented on documentation/modules/ROOT/pages/payloads.adoc
> +[source, turtle]
Please change this to enable variable evaluation in the code block:
```suggestion
[source,turtle,subs="attributes+,+quotes"]
```

2023-10-17 06:23 UTC, atextor commented on documentation/modules/ROOT/pages/payloads.adoc
> +Aspect Model
Make this line a third level header?
```suggestion
=== Aspect Model
```

2023-10-17 06:23 UTC, atextor commented on documentation/modules/ROOT/pages/payloads.adoc
> +Payload
Add a blank line before, then make this a third level header
```suggestion
=== Payload
```

2023-10-17 12:18 UTC, atextor requested changes

2023-10-17 12:18 UTC, atextor commented on documentation/modules/ROOT/pages/payloads.adoc
> +@prefix samm: <urn:samm:org.eclipse.esmf.samm:meta-model:2.0.0#> .
Please use the prefix variables in the same way, they are referred to in [Using Namespaces](https://eclipse-esmf.github.io/samm-specification/2.1.0/modeling-guidelines.html#using-namespaces):

```asciidoc
[source,turtle,subs="attributes+,+quotes"]
----
@prefix : <urn:samm:{example-ns}.myapplication:1.0.0#> .
@prefix samm: <{samm}> .
@prefix samm-c: <{samm-c}> .
@prefix samm-e: <{samm-e}> .
@prefix unit: <{unit}> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
----
```

2023-10-17 12:40 UTC, atextor approved these changes

2023-10-17 12:41 UTC, merged